var OA_output = new Array(); 
OA_output['18'] = '';
OA_output['18'] += "<"+"a href=\'http://www.radialnetwork.com:8088/openx/www/delivery/ck.php?oaparams=2__bannerid=48__zoneid=18__source=%7Bobfs%3A%7D__cb=a164fe53f2__oadest=http://www.quakelive.com\' target=\'_blank\'><"+"img src=\'http://iga.cachefly.net/web/qldefault/300_x_600.jpg\' width=\'300\' height=\'600\' alt=\'Quake Live\' title=\'Quake Live\' border=\'0\' /><"+"/a><"+"div id=\'beacon_a164fe53f2\' style=\'position: absolute; left: 0px; top: 0px; visibility: hidden;\'><"+"img src=\'http://www.radialnetwork.com:8088/openx/www/delivery/lg.php?bannerid=48&amp;campaignid=4&amp;zoneid=18&amp;source={obfs:}&amp;loc=http%3A%2F%2Fwww.quakelive.com%2F%23home%3Bstate%3D2%3Bdifficulty%3D1&amp;cb=a164fe53f2\' width=\'0\' height=\'0\' alt=\'\' style=\'width: 0px; height: 0px;\' /><"+"/div>\n";
OA_output['3'] = '';
OA_output['3'] += "<"+"a href=\'http://www.radialnetwork.com:8088/openx/www/delivery/ck.php?oaparams=2__bannerid=27__zoneid=3__source=%7Bobfs%3A%7D__cb=3454246595__oadest=http://www.quakelive.com\' target=\'_blank\'><"+"img src=\'http://iga.cachefly.net/web/qldefault/728_x_90.jpg\' width=\'728\' height=\'90\' alt=\'Quake Live\' title=\'Quake Live\' border=\'0\' /><"+"/a><"+"div id=\'beacon_3454246595\' style=\'position: absolute; left: 0px; top: 0px; visibility: hidden;\'><"+"img src=\'http://www.radialnetwork.com:8088/openx/www/delivery/lg.php?bannerid=27&amp;campaignid=4&amp;zoneid=3&amp;source={obfs:}&amp;loc=http%3A%2F%2Fwww.quakelive.com%2F%23home%3Bstate%3D2%3Bdifficulty%3D1&amp;cb=3454246595\' width=\'0\' height=\'0\' alt=\'\' style=\'width: 0px; height: 0px;\' /><"+"/div>\n";
OA_output['16'] = '';
OA_output['16'] += "<"+"a href=\'http://www.radialnetwork.com:8088/openx/www/delivery/ck.php?oaparams=2__bannerid=47__zoneid=16__source=%7Bobfs%3A%7D__cb=1b7d064d56__oadest=http://www.quakelive.com\' target=\'_blank\'><"+"img src=\'http://iga.cachefly.net/web/qldefault/300_x_250.jpg\' width=\'300\' height=\'250\' alt=\'Quake Live\' title=\'Quake Live\' border=\'0\' /><"+"/a><"+"div id=\'beacon_1b7d064d56\' style=\'position: absolute; left: 0px; top: 0px; visibility: hidden;\'><"+"img src=\'http://www.radialnetwork.com:8088/openx/www/delivery/lg.php?bannerid=47&amp;campaignid=4&amp;zoneid=16&amp;source={obfs:}&amp;loc=http%3A%2F%2Fwww.quakelive.com%2F%23home%3Bstate%3D2%3Bdifficulty%3D1&amp;cb=1b7d064d56\' width=\'0\' height=\'0\' alt=\'\' style=\'width: 0px; height: 0px;\' /><"+"/div>\n";
OA_output['22'] = '';

